import type { Metadata, Viewport } from "next";
import { Heebo, Suez_One } from "next/font/google";
import "./globals.css";
import "./miame-ultra.css";
import AmbientLight from "@/components/AmbientLight";
import MarkField from "@/components/MarkField";
import MotionFx from "@/components/MotionFx";
import ScrollProgress from "@/components/ScrollProgress";
import HeroIntro from "@/components/HeroIntro";
import ScrollTop from "@/components/ScrollTop";
import StaffToolbar from "@/components/StaffToolbar";
import MarketingScripts from "@/components/MarketingScripts";
import ConsentBanner from "@/components/ConsentBanner";
import { PRODUCT_PROPERTIES } from "@/lib/seo/product-jsonld";
import { MODELS } from "@/lib/models";
import { buildHomeFaqJsonLd } from "@/lib/home-faq";

// Gate the cinematic entrance before first paint (no flash, no-JS safe).
// Full sequence on first visit per session, a quick settle afterwards,
// and nothing at all for reduced-motion visitors.
const INTRO_GATE = `(function(){try{var d=document.documentElement;
if(matchMedia('(prefers-reduced-motion: reduce)').matches)return;
var s=sessionStorage.getItem('miame_intro');
d.classList.add('intro-go',s?'intro-quick':'intro-full');
sessionStorage.setItem('miame_intro','1');}catch(e){}})();`;

const heebo = Heebo({
  subsets: ["hebrew", "latin"],
  weight: ["300", "400", "500", "600", "700", "800", "900"],
  variable: "--font-heebo",
  display: "swap"
});

// Suez One — the MIA FOUR display type (Hebrew + Latin, single 400 weight).
// Wired as --font-display; used on hero/section display headings only.
const suezOne = Suez_One({
  subsets: ["hebrew", "latin"],
  weight: "400",
  variable: "--font-display",
  display: "swap"
});

const SITE_URL = "https://www.miame.co.il";
// Product schema uses the clean cutout of the actual Mia FOUR X4. The OG/share
// card is generated by app/opengraph-image.tsx (dark luxury, 1200×630).
const PRODUCT_IMAGE = "/mia-four-x4-hero.webp";

export const metadata: Metadata = {
  metadataBase: new URL(SITE_URL),
  title: {
    default: "MiaMe — החופש שלך על ארבעה גלגלים",
    template: "%s | MiaMe",
  },
  description:
    "ניידות חשמלית פרימיום במחיר חכם. בנה הצעת תשלום מותאמת תוך דקה וקבל אותה ישירות בוואטסאפ. מבית Leasing.co.il.",
  applicationName: "MiaMe",
  keywords: ["MiaMe", "רכב חשמלי", "ניידות חשמלית", "ליסינג", "השכרה", "Leasing.co.il"],
  alternates: { canonical: "/" },
  // Icons are resolved by the file conventions in app/ (favicon.ico, icon.svg,
  // icon.png, apple-icon.png) — those take precedence over a metadata.icons object,
  // so we let the files drive the <head> links and keep this object focused on the
  // rest of the metadata.
  openGraph: {
    title: "MiaMe — החופש שלך על ארבעה גלגלים",
    description:
      "ניידות חשמלית פרימיום במחיר חכם. הצעת תשלום מותאמת תוך דקה, ישירות לוואטסאפ.",
    url: SITE_URL,
    siteName: "MiaMe",
    locale: "he_IL",
    type: "website",
    // OG/share image is generated by app/opengraph-image.tsx (dark luxury, 1200×630).
  },
  twitter: {
    card: "summary_large_image",
    title: "MiaMe — החופש שלך על ארבעה גלגלים",
    description:
      "ניידות חשמלית פרימיום במחיר חכם. הצעת תשלום מותאמת תוך דקה, ישירות לוואטסאפ.",
  },
  robots: { index: true, follow: true },
};

// One Product/Offer node per live model (single source of truth: lib/models.ts),
// so prices can never drift from the catalogue.
const HOME_PRODUCTS = MODELS.map((m) => ({
  "@type": "Product",
  "@id": `${SITE_URL}/#product-${m.id}`,
  name: `MiaMe Four ${m.name}`,
  image: SITE_URL + PRODUCT_IMAGE,
  description: `MIA FOUR ${m.name} — ${m.tagline}. פלטפורמת 4 גלגלים מוגנת פטנט, סוללת ליתיום נשלפת 60V.`,
  brand: { "@type": "Brand", name: "MiaMe" },
  offers: {
    "@type": "Offer",
    priceCurrency: "ILS",
    price: m.price,
    availability: "https://schema.org/InStock",
    url: SITE_URL
  },
  additionalProperty: PRODUCT_PROPERTIES
}));

const JSON_LD = {
  "@context": "https://schema.org",
  "@graph": [
    {
      "@type": "WebSite",
      "@id": SITE_URL + "/#website",
      name: "MiaMe",
      alternateName: ["miame.co.il", "MiaMe.co.il"],
      url: SITE_URL + "/",
      inLanguage: "he-IL",
      publisher: { "@id": SITE_URL + "/#organization" }
    },
    {
      "@type": "Organization",
      "@id": SITE_URL + "/#organization",
      name: "MiaMe",
      url: SITE_URL,
      logo: SITE_URL + "/mia-four-logo.webp",
      description: "ניידות חשמלית פרימיום במחיר חכם, מבית Leasing.co.il.",
      contactPoint: {
        "@type": "ContactPoint",
        telephone: "+972-54-747-7477",
        contactType: "sales",
        areaServed: "IL",
        availableLanguage: ["he"]
      }
    },
    ...HOME_PRODUCTS,
    {
      "@type": "LocalBusiness",
      "@id": SITE_URL + "/#localbusiness",
      name: "MiaMe · חנות הדגל",
      image: SITE_URL + PRODUCT_IMAGE,
      url: SITE_URL,
      telephone: "+972-54-747-7477",
      address: {
        "@type": "PostalAddress",
        streetAddress: "אליעזר קפלן 21",
        addressLocality: "תל אביב",
        addressCountry: "IL"
      },
      priceRange: "₪₪"
    },
    buildHomeFaqJsonLd(SITE_URL + "/#faq")
  ]
};

export const viewport: Viewport = {
  // Ultra Color P Master: Pearl on light, Abyss on dark (= manifest theme_color).
  themeColor: [
    { media: "(prefers-color-scheme: light)", color: "#FDFBF6" },
    { media: "(prefers-color-scheme: dark)", color: "#04121F" }
  ],
  width: "device-width",
  initialScale: 1,
  viewportFit: "cover"
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="he" dir="rtl" className={`${heebo.variable} ${suezOne.variable}`}>
      <body>
        {/* WCAG 2.4.1 (Bypass Blocks): first focusable element jumps to content */}
        <a href="#main" className="skip-link">דילוג לתוכן הראשי</a>
        <script dangerouslySetInnerHTML={{ __html: INTRO_GATE }} />
        <ScrollProgress />
        <ScrollTop />
        <AmbientLight />
        <MarkField />
        {children}
        <MotionFx />
        <HeroIntro />
        <StaffToolbar />
        <ConsentBanner />
        <MarketingScripts />
        <script
          type="application/ld+json"
          dangerouslySetInnerHTML={{ __html: JSON.stringify(JSON_LD) }}
        />
      </body>
    </html>
  );
}
