import type { Metadata, Viewport } from "next";
import { SAME_AS } from "@/lib/brand-social";
import {
  MANUFACTURER_NAME,
  MANUFACTURER_NAME_HE,
  MANUFACTURER_URL,
  PRODUCT_ALTERNATE_NAMES,
  PRODUCT_CATEGORY_HE,
  PRODUCT_NAME,
  PRODUCT_NAME_HE,
} from "@/lib/content";
import { SALES_PHONE_E164 } from "@/lib/whatsapp";
import { Heebo, Suez_One, Space_Grotesk } from "next/font/google";
import "./globals.css";
import "./miame-ultra.css";
import "./miame-hero-v2.css";
import AmbientLight from "@/components/AmbientLight";
import CardSpotlight from "@/components/CardSpotlight";
import MarkField from "@/components/MarkField";
import MotionFx from "@/components/MotionFx";
import ScrollProgress from "@/components/ScrollProgress";
import HeroIntro from "@/components/HeroIntro";
import ScrollTop from "@/components/ScrollTop";
import StaffToolbar from "@/components/StaffToolbar";
import MarketingScripts from "@/components/MarketingScripts";
import ConsentBanner from "@/components/ConsentBanner";
import { PRODUCT_PROPERTIES } from "@/lib/seo/product-jsonld";
import { MODELS } from "@/lib/models";
import { spyqeProductJsonLd } from "@/lib/spyqe";

// Gate the cinematic entrance before first paint (no flash, no-JS safe).
// Full sequence on first visit per session, a quick settle afterwards,
// and nothing at all for reduced-motion visitors.
const INTRO_GATE = `(function(){try{var d=document.documentElement;
if(matchMedia('(prefers-reduced-motion: reduce)').matches)return;
var s=sessionStorage.getItem('miame_intro');
d.classList.add('intro-go',s?'intro-quick':'intro-full');
sessionStorage.setItem('miame_intro','1');}catch(e){}})();`;

const heebo = Heebo({
  subsets: ["hebrew", "latin"],
  weight: ["300", "400", "500", "600", "700", "800", "900"],
  variable: "--font-heebo",
  display: "swap"
});

// Suez One — the MIA FOUR display type (Hebrew + Latin, single 400 weight).
// Wired as --font-display; used on hero/section display headings only.
const suezOne = Suez_One({
  subsets: ["hebrew", "latin"],
  weight: "400",
  variable: "--font-display",
  display: "swap"
});

// Space Grotesk — the technical-Latin voice (eyebrow, MIA FOUR, FREE FEEL, numbers)
// of the Ultra Master hero. Wired as --font-grotesk. (V3 §3)
const spaceGrotesk = Space_Grotesk({
  subsets: ["latin"],
  weight: ["500", "700"],
  variable: "--font-grotesk",
  display: "swap"
});

const SITE_URL = "https://www.miame.co.il";
// Product schema uses the clean cutout of the actual Mia FOUR 4×4 Pro Max. The OG/share
// card is generated by app/opengraph-image.tsx (dark luxury, 1200×630).
const PRODUCT_IMAGE = "/mia-four-x4-hero.webp";

export const metadata: Metadata = {
  metadataBase: new URL(SITE_URL),
  // THE TITLE NAMES THE THING NOW. Measured 2026-09-01, it read
  // "MiaMe · החופש שלך על ארבעה גלגלים" — poetic, and invisible: neither the
  // product (מיה פור / MIA FOUR) nor the category (קלנועית) appeared in the most
  // heavily weighted element on the strongest page of the domain. Someone
  // searching either term saw a title that answered neither. The brand line is
  // kept, second, where it still reads as a promise rather than a keyword.
  title: {
    default: `${PRODUCT_NAME_HE} · ${PRODUCT_CATEGORY_HE} חשמלית 4 גלגלים | MiaMe`,
    template: "%s | MiaMe",
  },
  // THE SNIPPET NAMES THE THING TOO. The title was fixed on 2026-09-01 and the H1
  // on the same day; the description — the two lines Google prints under that
  // title, and the passage an answer engine quotes — was not re-read, and still
  // opened on "ניידות חשמלית פרימיום": the exact phrase the H1 comment above
  // calls one nobody searches. It named neither the product (מיה פור) nor what
  // the thing legally IS (קלנועית), on the one string that appears beside every
  // result for the domain. Both are now first, and the imperative is plural, like
  // every other call to action on the site ("בנו" · "צפו" · "גררו"), not "בנה".
  description:
    `${PRODUCT_NAME_HE} · ${PRODUCT_CATEGORY_HE} חשמלית פרימיום על 4 גלגלים. בנו הצעת תשלום מותאמת תוך דקה וקבלו אותה ישירות בוואטסאפ. מבית Leasing.co.il.`,
  applicationName: "MiaMe",
  // "רכב חשמלי" was removed, and not for SEO: the site's own legal page states
  // that MIA FOUR is classified as a קלנועית and is NOT a vehicle. A keyword that
  // contradicts your own compliance copy is a liability before it is a miss.
  keywords: [
    PRODUCT_NAME_HE,
    PRODUCT_NAME,
    PRODUCT_CATEGORY_HE,
    `${PRODUCT_CATEGORY_HE} חשמלית`,
    `${PRODUCT_CATEGORY_HE} 4 גלגלים`,
    `${PRODUCT_CATEGORY_HE} מיה`,
    MANUFACTURER_NAME_HE,
    MANUFACTURER_NAME,
    "ניידות חשמלית",
    "MiaMe",
    "Leasing.co.il",
  ],
  alternates: { canonical: "/" },
  // Icons are resolved by the file conventions in app/ (favicon.ico, icon.svg,
  // icon.png, apple-icon.png) — those take precedence over a metadata.icons object,
  // so we let the files drive the <head> links and keep this object focused on the
  // rest of the metadata.
  openGraph: {
    title: `${PRODUCT_NAME_HE} · ${PRODUCT_CATEGORY_HE} חשמלית | MiaMe`,
    description:
      `${PRODUCT_NAME_HE} · ${PRODUCT_CATEGORY_HE} חשמלית פרימיום על 4 גלגלים. הצעת תשלום מותאמת תוך דקה, ישירות לוואטסאפ.`,
    url: SITE_URL,
    siteName: "MiaMe",
    locale: "he_IL",
    type: "website",
    // OG/share image is generated by app/opengraph-image.tsx (dark luxury, 1200×630).
  },
  // CARD TYPE ONLY — deliberately no title and no description.
  //
  // Next merges metadata one top-level key at a time, so a `twitter.title`
  // declared here is inherited WHOLE by every route that does not declare its
  // own. All twelve non-home pages therefore served the homepage's X card:
  // /klnoit-shetach announced "MiaMe · החופש שלך על ארבעה גלגלים" over its own
  // title. With only `card` set, Next's postProcessMetadata fills twitter:title
  // and twitter:description from each route's openGraph — and the homepage still
  // resolves to these exact two strings, because its openGraph above already
  // says them. Measured on a real build: 11 of 13 routes now carry their own.
  twitter: {
    card: "summary_large_image",
  },
  robots: { index: true, follow: true },
};

// One Product/Offer node per live model (single source of truth: lib/models.ts),
// so prices can never drift from the catalogue.
const HOME_PRODUCTS = MODELS.map((m) => ({
  "@type": "Product",
  "@id": `${SITE_URL}/#product-${m.id}`,
  // WAS `MiaMe Four ${m.name}` — a name that exists in NO source. The hero says
  // MIA FOUR, the corpus says מיה פור, the manufacturer says MIA FOUR; nothing
  // anywhere says "MiaMe Four". It is the site's name welded onto the product's,
  // sitting in the one place a machine reads it as authoritative.
  name: `${PRODUCT_NAME} ${m.name}`,
  // The entity-resolution anchor: one declaration that MIA FOUR, מיה פור and מיה
  // are the same thing. This is what earns the Hebrew queries — without repeating
  // a single word in the prose, which is the line between naming and stuffing.
  alternateName: [`${PRODUCT_NAME_HE} ${m.name}`, ...PRODUCT_ALTERNATE_NAMES],
  category: PRODUCT_CATEGORY_HE,
  image: SITE_URL + PRODUCT_IMAGE,
  description: `${PRODUCT_NAME} ${m.name} (${PRODUCT_NAME_HE}), ${m.tagline}. ${PRODUCT_CATEGORY_HE} חשמלית על פלטפורמת 4 גלגלים מוגנת פטנט, סוללת ליתיום נשלפת 60V. מתוצרת ${MANUFACTURER_NAME} (${MANUFACTURER_NAME_HE}).`,
  // WAS `brand: MiaMe`. MiaMe is the SELLER, not the brand — and saying otherwise
  // told every engine that the manufacturer's reputation belongs to the shop.
  // The brand is the product line; the manufacturer is its own Organization; the
  // seller moves down into the Offer, which is where schema.org puts a retailer.
  brand: {
    "@type": "Brand",
    name: PRODUCT_NAME,
    alternateName: [...PRODUCT_ALTERNATE_NAMES],
  },
  manufacturer: {
    "@type": "Organization",
    name: MANUFACTURER_NAME,
    alternateName: [MANUFACTURER_NAME_HE],
    // Provenance, machine-readable only. `url` is what lets an engine resolve this
    // node against the real global company rather than treating it as a bare string
    // — the difference between a name and an identified entity.
    url: MANUFACTURER_URL,
  },
  offers: {
    "@type": "Offer",
    priceCurrency: "ILS",
    price: m.price,
    availability: "https://schema.org/InStock",
    url: SITE_URL,
    seller: { "@id": `${SITE_URL}/#organization` }
  },
  additionalProperty: PRODUCT_PROPERTIES
}));

/** The commercial graph, rendered by app/page.tsx rather than by this layout.
 *  Exported as a finished string so the page does not have to re-import SITE_URL,
 *  MODELS and the SPYQE builder just to rebuild something that already exists. */
export const HOME_PRODUCTS_JSONLD = JSON.stringify({
  "@context": "https://schema.org",
  "@graph": [...HOME_PRODUCTS, spyqeProductJsonLd(SITE_URL)],
});

const JSON_LD = {
  "@context": "https://schema.org",
  "@graph": [
    {
      "@type": "WebSite",
      "@id": SITE_URL + "/#website",
      name: "MiaMe",
      alternateName: ["miame.co.il", "MiaMe.co.il"],
      url: SITE_URL + "/",
      inLanguage: "he-IL",
      publisher: { "@id": SITE_URL + "/#organization" }
    },
    {
      "@type": "Organization",
      "@id": SITE_URL + "/#organization",
      name: "MiaMe",
      url: SITE_URL,
      logo: SITE_URL + "/mia-four-logo.webp",
      description: `${PRODUCT_NAME_HE} · ${PRODUCT_CATEGORY_HE} חשמלית פרימיום, מבית Leasing.co.il.`,
      // `sameAs` — the machine-readable assertion that this business and the
      // accounts listed are ONE entity. It carries the BRAND's profiles and only
      // those: the owner's personal accounts stay unlinked and unnamed in public,
      // which is why this derives from lib/brand-social.ts rather than naming a
      // URL here. Omitted entirely while the registry is empty — schema.org reads
      // an absent `sameAs` as "not stated", which is honest, whereas an empty
      // array is noise and a wrong profile is a false claim.
      ...(SAME_AS.length ? { sameAs: SAME_AS } : {}),
      areaServed: { "@type": "Country", name: "IL" },
      contactPoint: {
        "@type": "ContactPoint",
        // A SEVENTH spelling of the number lived here, and it is the one that
        // matters most: contactPoint.telephone is what search and answer engines
        // read and repeat. It is now derived, in E.164 — the machine form the
        // schema expects — so it cannot drift from the line the funnel dials.
        telephone: SALES_PHONE_E164,
        contactType: "sales",
        areaServed: "IL",
        availableLanguage: ["he"]
      }
    },
    // NOTE — and the four Product nodes are gone from here too, for the reason
    // the FAQPage note below already states in full. MEASURED 2026-09-09: this
    // graph put four Product+Offer nodes, each `InStock` with a price, on ALL
    // thirteen routes — including /legal/privacy, /legal/terms and
    // /legal/accessibility, which are `index: true` and render no product at
    // all, plus /thank-you and /marketplace-preview. An Offer is a commercial
    // assertion about the page it stands on; a privacy policy that declares four
    // priced, in-stock products is the same content/markup mismatch that cost
    // the FAQPage its rich result, in a shape that touches money. They now ship
    // from app/page.tsx, beside the models the page actually renders.
    // NOTE — there is deliberately NO LocalBusiness node here.
    // MiaMe sells and delivers nationwide; it does not publish a storefront.
    // The previous node published a named physical storefront and its street
    // address. The sales campaign removed both from every visible surface, and
    // leaving the schema node behind would have kept that entity alive for
    // search engines after the page stopped claiming it. The Organization node
    // above carries the brand, the sales contactPoint and the area served.
    // Guarded by test/salesCampaign.test.ts.
    //
    // NOTE — and there is deliberately no FAQPage node here any more, for the
    // same reason in a different shape. This graph is rendered by the ROOT
    // layout, so whatever stands in it is injected into all thirteen routes.
    // Twelve of them render none of the six homepage answers, and Google's
    // FAQPage guidance is explicit that the markup must mirror content visible
    // on the SAME page — six answers a visitor cannot read is exactly the
    // mismatch that costs the rich result. The node now ships from app/page.tsx,
    // beside the accordion that renders it.
  ]
};

export const viewport: Viewport = {
  // ONE COLOUR, BECAUSE THE SITE HAS ONE THEME (measured 2026-09-09).
  //
  // This declared Pearl (#FDFBF6) for light and Abyss (#04121F) for dark. Neither
  // was what the browser painted. There is not a single `prefers-color-scheme` rule
  // in app/globals.css, app/miame-ultra.css, app/miame-hero-v2.css or
  // styles/tokens.miame.css — grep returns zero — and app/globals.css:917 pins
  // `:root{color-scheme:light}`. The page is `html{background:var(--snow)}`
  // (globals.css:66) = #ffffff, always, on every device. So the dark entry drew a
  // near-black browser bar directly above a white page for every visitor whose
  // phone is in dark mode, which is most of them; and the light entry was off by a
  // shade from the white it sat above.
  //
  // The NIGHT DRIVE half of styles/tokens.miame.css is not deleted — it is the
  // declared vocabulary for the dark sections the design uses deliberately. But a
  // token palette is not a theme: when a real `prefers-color-scheme` implementation
  // ships, the second entry comes back with it, in the same change.
  themeColor: "#FFFFFF",
  width: "device-width",
  initialScale: 1,
  viewportFit: "cover"
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="he" dir="rtl" className={`${heebo.variable} ${suezOne.variable} ${spaceGrotesk.variable}`}>
      <body>
        {/* WCAG 2.4.1 (Bypass Blocks): first focusable element jumps to content */}
        <a href="#main" className="skip-link">דילוג לתוכן הראשי</a>
        <script dangerouslySetInnerHTML={{ __html: INTRO_GATE }} />
        <ScrollProgress />
        <ScrollTop />
        <AmbientLight />
        <CardSpotlight />
        <MarkField />
        {children}
        <MotionFx />
        <HeroIntro />
        <StaffToolbar />
        <ConsentBanner />
        <MarketingScripts />
        <script
          type="application/ld+json"
          dangerouslySetInnerHTML={{ __html: JSON.stringify(JSON_LD) }}
        />
      </body>
    </html>
  );
}
