import type { Metadata, Viewport } from "next";
import { SALES_PHONE_E164 } from "@/lib/whatsapp";
import { Heebo, Suez_One, Space_Grotesk } from "next/font/google";
import "./globals.css";
import "./miame-ultra.css";
import "./miame-hero-v2.css";
import AmbientLight from "@/components/AmbientLight";
import MarkField from "@/components/MarkField";
import MotionFx from "@/components/MotionFx";
import ScrollProgress from "@/components/ScrollProgress";
import HeroIntro from "@/components/HeroIntro";
import ScrollTop from "@/components/ScrollTop";
import StaffToolbar from "@/components/StaffToolbar";
import MarketingScripts from "@/components/MarketingScripts";
import ConsentBanner from "@/components/ConsentBanner";
import { PRODUCT_PROPERTIES } from "@/lib/seo/product-jsonld";
import { MODELS } from "@/lib/models";
import { spyqeProductJsonLd } from "@/lib/spyqe";

// Gate the cinematic entrance before first paint (no flash, no-JS safe).
// Full sequence on first visit per session, a quick settle afterwards,
// and nothing at all for reduced-motion visitors.
const INTRO_GATE = `(function(){try{var d=document.documentElement;
if(matchMedia('(prefers-reduced-motion: reduce)').matches)return;
var s=sessionStorage.getItem('miame_intro');
d.classList.add('intro-go',s?'intro-quick':'intro-full');
sessionStorage.setItem('miame_intro','1');}catch(e){}})();`;

const heebo = Heebo({
  subsets: ["hebrew", "latin"],
  weight: ["300", "400", "500", "600", "700", "800", "900"],
  variable: "--font-heebo",
  display: "swap"
});

// Suez One — the MIA FOUR display type (Hebrew + Latin, single 400 weight).
// Wired as --font-display; used on hero/section display headings only.
const suezOne = Suez_One({
  subsets: ["hebrew", "latin"],
  weight: "400",
  variable: "--font-display",
  display: "swap"
});

// Space Grotesk — the technical-Latin voice (eyebrow, MIA FOUR, FREE FEEL, numbers)
// of the Ultra Master hero. Wired as --font-grotesk. (V3 §3)
const spaceGrotesk = Space_Grotesk({
  subsets: ["latin"],
  weight: ["500", "700"],
  variable: "--font-grotesk",
  display: "swap"
});

const SITE_URL = "https://www.miame.co.il";
// Product schema uses the clean cutout of the actual Mia FOUR 4×4 Pro Max. The OG/share
// card is generated by app/opengraph-image.tsx (dark luxury, 1200×630).
const PRODUCT_IMAGE = "/mia-four-x4-hero.webp";

export const metadata: Metadata = {
  metadataBase: new URL(SITE_URL),
  title: {
    default: "MiaMe · החופש שלך על ארבעה גלגלים",
    template: "%s | MiaMe",
  },
  description:
    "ניידות חשמלית פרימיום במחיר חכם. בנה הצעת תשלום מותאמת תוך דקה וקבל אותה ישירות בוואטסאפ. מבית Leasing.co.il.",
  applicationName: "MiaMe",
  keywords: ["MiaMe", "רכב חשמלי", "ניידות חשמלית", "ליסינג", "השכרה", "Leasing.co.il"],
  alternates: { canonical: "/" },
  // Icons are resolved by the file conventions in app/ (favicon.ico, icon.svg,
  // icon.png, apple-icon.png) — those take precedence over a metadata.icons object,
  // so we let the files drive the <head> links and keep this object focused on the
  // rest of the metadata.
  openGraph: {
    title: "MiaMe · החופש שלך על ארבעה גלגלים",
    description:
      "ניידות חשמלית פרימיום במחיר חכם. הצעת תשלום מותאמת תוך דקה, ישירות לוואטסאפ.",
    url: SITE_URL,
    siteName: "MiaMe",
    locale: "he_IL",
    type: "website",
    // OG/share image is generated by app/opengraph-image.tsx (dark luxury, 1200×630).
  },
  // CARD TYPE ONLY — deliberately no title and no description.
  //
  // Next merges metadata one top-level key at a time, so a `twitter.title`
  // declared here is inherited WHOLE by every route that does not declare its
  // own. All twelve non-home pages therefore served the homepage's X card:
  // /klnoit-shetach announced "MiaMe · החופש שלך על ארבעה גלגלים" over its own
  // title. With only `card` set, Next's postProcessMetadata fills twitter:title
  // and twitter:description from each route's openGraph — and the homepage still
  // resolves to these exact two strings, because its openGraph above already
  // says them. Measured on a real build: 11 of 13 routes now carry their own.
  twitter: {
    card: "summary_large_image",
  },
  robots: { index: true, follow: true },
};

// One Product/Offer node per live model (single source of truth: lib/models.ts),
// so prices can never drift from the catalogue.
const HOME_PRODUCTS = MODELS.map((m) => ({
  "@type": "Product",
  "@id": `${SITE_URL}/#product-${m.id}`,
  name: `MiaMe Four ${m.name}`,
  image: SITE_URL + PRODUCT_IMAGE,
  description: `MIA FOUR ${m.name}, ${m.tagline}. פלטפורמת 4 גלגלים מוגנת פטנט, סוללת ליתיום נשלפת 60V.`,
  brand: { "@type": "Brand", name: "MiaMe" },
  offers: {
    "@type": "Offer",
    priceCurrency: "ILS",
    price: m.price,
    availability: "https://schema.org/InStock",
    url: SITE_URL
  },
  additionalProperty: PRODUCT_PROPERTIES
}));

const JSON_LD = {
  "@context": "https://schema.org",
  "@graph": [
    {
      "@type": "WebSite",
      "@id": SITE_URL + "/#website",
      name: "MiaMe",
      alternateName: ["miame.co.il", "MiaMe.co.il"],
      url: SITE_URL + "/",
      inLanguage: "he-IL",
      publisher: { "@id": SITE_URL + "/#organization" }
    },
    {
      "@type": "Organization",
      "@id": SITE_URL + "/#organization",
      name: "MiaMe",
      url: SITE_URL,
      logo: SITE_URL + "/mia-four-logo.webp",
      description: "ניידות חשמלית פרימיום במחיר חכם, מבית Leasing.co.il.",
      // NO `sameAs`. Deliberate, and the reason is worth keeping next to the
      // node it is absent from: `sameAs` is the machine-readable assertion that
      // this business and the accounts it lists are ONE entity. The only
      // accounts available are the owner's PERSONAL ones, and the standing
      // instruction is that business and private stay separate in public — the
      // accounts work the campaign from behind the scenes, unnamed and unlinked.
      // Omitting the property states nothing, which is the honest outcome here;
      // listing a personal profile would publish exactly the link being avoided.
      // A BRAND account, if one is ever opened, belongs here and nothing else does.
      areaServed: { "@type": "Country", name: "IL" },
      contactPoint: {
        "@type": "ContactPoint",
        // A SEVENTH spelling of the number lived here, and it is the one that
        // matters most: contactPoint.telephone is what search and answer engines
        // read and repeat. It is now derived, in E.164 — the machine form the
        // schema expects — so it cannot drift from the line the funnel dials.
        telephone: SALES_PHONE_E164,
        contactType: "sales",
        areaServed: "IL",
        availableLanguage: ["he"]
      }
    },
    ...HOME_PRODUCTS,
    // SPYQE is a PRE-ORDER, not stock, and it carries its own properties — the
    // shared PRODUCT_PROPERTIES list quotes a MIA FOUR motor rating.
    spyqeProductJsonLd(SITE_URL),
    // NOTE — there is deliberately NO LocalBusiness node here.
    // MiaMe sells and delivers nationwide; it does not publish a storefront.
    // The previous node published a named physical storefront and its street
    // address. The sales campaign removed both from every visible surface, and
    // leaving the schema node behind would have kept that entity alive for
    // search engines after the page stopped claiming it. The Organization node
    // above carries the brand, the sales contactPoint and the area served.
    // Guarded by test/salesCampaign.test.ts.
    //
    // NOTE — and there is deliberately no FAQPage node here any more, for the
    // same reason in a different shape. This graph is rendered by the ROOT
    // layout, so whatever stands in it is injected into all thirteen routes.
    // Twelve of them render none of the six homepage answers, and Google's
    // FAQPage guidance is explicit that the markup must mirror content visible
    // on the SAME page — six answers a visitor cannot read is exactly the
    // mismatch that costs the rich result. The node now ships from app/page.tsx,
    // beside the accordion that renders it.
  ]
};

export const viewport: Viewport = {
  // Ultra Color P Master: Pearl on light, Abyss on dark (= manifest theme_color).
  themeColor: [
    { media: "(prefers-color-scheme: light)", color: "#FDFBF6" },
    { media: "(prefers-color-scheme: dark)", color: "#04121F" }
  ],
  width: "device-width",
  initialScale: 1,
  viewportFit: "cover"
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="he" dir="rtl" className={`${heebo.variable} ${suezOne.variable} ${spaceGrotesk.variable}`}>
      <body>
        {/* WCAG 2.4.1 (Bypass Blocks): first focusable element jumps to content */}
        <a href="#main" className="skip-link">דילוג לתוכן הראשי</a>
        <script dangerouslySetInnerHTML={{ __html: INTRO_GATE }} />
        <ScrollProgress />
        <ScrollTop />
        <AmbientLight />
        <MarkField />
        {children}
        <MotionFx />
        <HeroIntro />
        <StaffToolbar />
        <ConsentBanner />
        <MarketingScripts />
        <script
          type="application/ld+json"
          dangerouslySetInnerHTML={{ __html: JSON.stringify(JSON_LD) }}
        />
      </body>
    </html>
  );
}
